FROM ubuntu:14.04

ENV DEBIAN_FRONTEND noninteractive

# Need wine 1.7.xx for this all to work, so we'll use the PPA:
RUN dpkg --add-architecture i386 \
 && echo "deb http://ppa.launchpad.net/ubuntu-wine/ppa/ubuntu trusty main" >> /etc/apt/sources.list.d/wine.list \
 && apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 5A9A06AEF9CB8DB0 \
 && apt-get update \
 && apt-get install --no-install-recommends -qfy wine1.7 winetricks \
 && apt-get clean
RUN apt-get -qfy install ca-certificates

RUN useradd -d /app -m app
USER app
ENV HOME /app
RUN mkdir -p /app/src
RUN mkdir -p /app/.profile.d
WORKDIR /app/src

ENV WINEARCH win32
# Silence all the "fixme: blah blah blah" messages from wine
ENV WINEDEBUG fixme-all

# Install the .net 4.0 runtime (not actually required for python!)
RUN wineboot \
 && winetricks -q dotnet40 \
 && while pgrep wineserver >/dev/null; do echo "Waiting for wineserver"; sleep 1; done \
 && rm -rf $HOME/.cache/winetricks

USER root
RUN apt-get update && apt-get install -y git &&\
    apt-get install -y xvfb && \
    apt-get install -y sudo
RUN echo "root:root" | chpasswd
RUN echo "app:app" | chpasswd
RUN echo "app ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

USER app

RUN mkdir -p /app/.cache/winetricks/dotnet30
COPY netframework3.exe /app/.cache/winetricks/dotnet30